server:
  port: 80
  
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://nico.com:8000/eureka/,http://nico25.com:8001/eureka/,http://nico252.com:8002/eureka/

---
spring:
   profiles: dev
   
server:
  port: 80
  
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://nico.com:8000/eureka/,http://nico25.com:8001/eureka/,http://nico252.com:8002/eureka/
      
---
spring:
   profiles: test
   
server:
  port: 81
  
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://nico.com:8000/eureka/,http://nico25.com:8001/eureka/,http://nico252.com:8002/eureka/
